[phases.setup]
nixPkgs = ["...", "libGL", "glib", "xorg.libxcb", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libSM", "xorg.libICE"]
nixLibs = ["...", "libGL", "glib", "xorg.libxcb", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libSM", "xorg.libICE"]
