services:
  - type: web
    name: face-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python download_weights.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DEEPFACE_HOME
        value: /opt/render/project/src/.venv
      - key: OMP_NUM_THREADS
        value: "1"
      - key: TF_NUM_INTRAOP_THREADS
        value: "1"
      - key: TF_NUM_INTEROP_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
      - key: VECLIB_MAXIMUM_THREADS
        value: "1"
      - key: NUMEXPR_NUM_THREADS
        value: "1"
